name: Profile Views

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Profile Views
        uses: anuraghazra/github-readme-stats@master
        with:
          username: herawenn
          count_private: true
          show_icons: true
          theme: tokyonight
